name: 🔼 Package Update Request
description: Request an update to an outdated package
title: '[Update Request]: '
labels:
- update-request
body:
- type: markdown
  attributes:
    value: |
      **Example Title**

      Please use the following format for the title

      > [Update Request]: PDQ Deploy 1.2.5

      Where `1.2.5` is the **current version of the software** (not the version available on the Chocolatey community repository).
- type: checkboxes
  id: checklist
  attributes:
    label: Checklist
    description: Before continuing, please confirm you have done the following.
    options:
    - label: >-
        I have verified that there are no pending versions in the `Version History` section of the Chocolatey package [More info](https://github.com/asheroto/ChocolateyPackages/blob/master/README.md#updates)
      required: true
    - label: >-
        I have specified the name of the package and the current version of the software in the issue's title
      required: true
- type: input
  id: package-name
  attributes:
    label: Package Name
    description: Name of the Chocolatey package (not the software name) on the [Chocolatey Community Repository](https://community.chocolatey.org/packages)
    placeholder: pdq-deploy
  validations:
    required: true
- type: input
  id: software-name
  attributes:
    label: Software Name
    description: Name of the software
    placeholder: PDQ Deploy
  validations:
    required: true
- type: input
  id: package-url
  attributes:
    label: Package URL
    description: URL of the package on the [Chocolatey Community Repository](https://community.chocolatey.org/packages)
    placeholder: https://community.chocolatey.org/packages/pdq-deploy
- type: input
  id: current-choco-version
  attributes:
    label: Current Chocolatey Version
    description: Current version available on the Chocolatey community repository at the time of creating this issue
    placeholder: 1.2.3
- type: input
  id: current-software-version
  attributes:
    label: Current Software Version
    description: Current version of the software available at the time of creating this issue
    placeholder: 1.2.5
- type: textarea
  id: comments
  attributes:
    label: Comments
    description: |
      Please include any other information here that you feel may be relevant
